on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.TEAM_APP_ID }}
          private-key: ${{ secrets.TEAM_APP_KEY }}

      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      
      - name: Upload model to Github Release
        uses: softprops/action-gh-release@v1
        with:
          files: models/sentiment_model.pkl
          name: sentiment_model.pkl
          body: |
            This is the sentiment model trained on the latest data.
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
