on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

name: release-please

jobs:
  release-please:
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      upload_url: ${{ steps.release.outputs.upload_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.TEAM_APP_ID }}
          private-key: ${{ secrets.TEAM_APP_KEY }}

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  attach-model:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{needs.release-please.outputs.release_created}}
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.TEAM_APP_ID }}
          private-key: ${{ secrets.TEAM_APP_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Download model from DVC
        run: |
          pip install dvc[gdrive]
          echo '${{ secrets.SERVICE_KEY }}' > service_key.json
          dvc pull --force
          ls models/
          
      - name: Upload model to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.release-please.outputs.upload_url }}
          asset_path: models/sentiment_model.pkl
          asset_name: sentiment_model.pkl
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}


      - name: Upload model to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.release-please.outputs.upload_url }}
          asset_path: models/bow_sentiment_model.pkl
          asset_name: bow_sentiment_model.pkl
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
