on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.TEAM_APP_ID }}
          private-key: ${{ secrets.TEAM_APP_KEY }}

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Download model from DVC
        uses: actions/download-artifact@v4
        with:
          name: dvc-model
          path: models
      

      - name: Upload model to Release
        if: ${{ steps.release.outputs.release_created  == 'true' }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: models/sentiment_model.pkl 
          asset_name: sentiment_model.pkl
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

